apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
  namespace: tekton-demo
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye World!"
